"""initial schema

Revision ID: 19a673b79a25
Revises: 
Create Date: 2026-03-30 11:38:36.852655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19a673b79a25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_groups_cache',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('dn', sa.String(length=512), nullable=False),
    sa.Column('cn', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=True),
    sa.Column('admin_user', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cluster_nodes',
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('portal_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rdp_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tech_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), server_default=sa.text('3389'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tech_name')
    )
    op.create_table('rdp_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority >= 0', name='ck_rdp_templates_priority_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('connection_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('server_display', sa.String(length=255), nullable=True),
    sa.Column('server_address', sa.String(length=255), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bytes_to_client', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_to_backend', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('disconnect_reason', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['rdp_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conn_history_started', 'connection_history', ['started_at'], unique=False)
    op.create_index('idx_conn_history_user', 'connection_history', ['username'], unique=False)
    op.create_table('server_group_bindings',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('ad_group_guid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['rdp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'ad_group_guid')
    )
    op.create_table('template_group_bindings',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('ad_group_guid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['rdp_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'ad_group_guid')
    )
    op.create_table('connection_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conn_events_conn_id', 'connection_events', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conn_events_conn_id', table_name='connection_events')
    op.drop_table('connection_events')
    op.drop_table('template_group_bindings')
    op.drop_table('server_group_bindings')
    op.drop_index('idx_conn_history_user', table_name='connection_history')
    op.drop_index('idx_conn_history_started', table_name='connection_history')
    op.drop_table('connection_history')
    op.drop_table('rdp_templates')
    op.drop_table('rdp_servers')
    op.drop_table('portal_settings')
    op.drop_table('cluster_nodes')
    op.drop_table('admin_users')
    op.drop_table('admin_audit_log')
    op.drop_table('ad_groups_cache')
    # ### end Alembic commands ###
